import React from "react";

import {
  AnnotationPin,
  AutoGrid,
  Avatar,
  Breadcrumb,
  Button,
  CommentThread,
  CrumbMenu,
  Disclosure,
  Eyebrow,
  FileList,
  GroupBand,
  IconButton,
  Input,
  LinkRow,
  LoadMore,
  MentionComposer,
  MentionText,
  Menu,
  MetricCard,
  Modal,
  Popover,
  RowActions,
  ScrollDock,
  SearchableList,
  SectionHeading,
  SegmentedControl,
  SelectableRow,
  StatusPill,
  SurfaceState,
  Timeline,
  TreeView,
  visuallyHiddenStyle,
} from "@/arkcase";
import {createReviewUI} from "@/arkcase/review-ui/review-ui.jsx";

/**
 * The project-owned review controls (contract correction 4), built once from
 * the application's React and the vendored ArkCase components.
 */
const controls = {
  AnnotationPin,
  AutoGrid,
  Avatar,
  Breadcrumb,
  Button,
  CommentThread,
  CrumbMenu,
  Disclosure,
  Eyebrow,
  FileList,
  GroupBand,
  IconButton,
  Input,
  LinkRow,
  LoadMore,
  MentionComposer,
  MentionText,
  Menu,
  MetricCard,
  Modal,
  Popover,
  RowActions,
  ScrollDock,
  SearchableList,
  SectionHeading,
  SegmentedControl,
  SelectableRow,
  StatusPill,
  SurfaceState,
  Timeline,
  TreeView,
};
// The review modules also read `visuallyHiddenStyle`, a style object rather than a
// component, to hide the breadcrumb's h1 while the docked list names the artifact. The
// declared controls map holds components only, so it joins the same object here.
Object.assign(controls, {visuallyHiddenStyle});
const reviewUi = createReviewUI(React, controls);

export const {
  ActivityFeed,
  ActivityHeader,
  ActivityToolbar,
  ArtifactBreadcrumb,
  ArtifactLinks,
  DesignGallery,
  DesignLibrary,
  FileGroups,
  GalleryPlaceholder,
  PageMenu,
  PagePicker,
  VersionList,
  VersionMenu,
} = reviewUi;
export type {
  ActivityArtifactGroup,
  ActivityBurst,
  ActivityEntry,
  ActivityEvent,
  ActivityFeedProps,
  ActivityHeaderProps,
  ActivityMetric,
  ActivityToolbarProps,
  ArtifactBreadcrumbProps,
  ArtifactFile,
  ArtifactLinkRow,
  ArtifactPage as ReviewPage,
  DesignLibraryProps,
  GalleryItem,
  GalleryKind,
  LibraryGrouping,
  LibraryItem,
  LibrarySort,
  PageMenuProps,
  PagePickerProps,
  VersionListEntry,
  VersionListProps,
  VersionMenuEntry,
  VersionMenuProps,
} from "@/arkcase/review-ui/review-ui.jsx";
